Algoritmo "Problema Soma - Desafio 4 "
// Disciplina: [Linguagem e Lógica de Programação]
// Professor: Prof Dr. Nelio Alves
// Descrição: : Fazer um programa para ler dois valores inteiros X e Y,
// e depois mostrar na tela o valor da soma destes números.

Var
x , y , soma : inteiro

Inicio
   Escreval("Digite o valor de x :")
   leia(x)
   Escreval("Digite o valor de y :")
   leia(y)
   soma <- x + y
   Escreval("O valor de x + y = ", soma)


Fimalgoritmo